"""
This will create an excel file that can be used to print out the turkey vouchers for 2017-?

"""
import string
import random
import xlsxwriter


YEAR = '2019'
VOUCHER_MAX = 4500
turkey_output = f'products/{YEAR}_voucher_run.xlsx'

def key_code_generator(number):
    '''
    This generates the a _number_ amount of
    10 character long ascii character codes and
    returns a set of them
    At the moment we only use digits becuase there is a
    chance that random words could be spelled out in
    the ascii characters
    '''
    #chars = string.digits + string.ascii_letters
    chars = string.digits 
    codes = set()
    while len(codes) < number:
        codes.add(''.join(random.sample(chars, 10)))
    return codes

def code_string(code_set):
    '''
    This takes the key codes generated by the key_code_generator() function
    and returns a list of them formatted with a sequential number 1... and
    a space 5 characters space 5 characters
    i.e. 1  alk4 3kdS
    '''
    number = 1
    out = []
    for code in code_set:
        string = f'{number}  {YEAR} {code[:5]} {code[5:]}'
        out.append(string)
        number += 1
    return out
   
def write_turkey_vouchers(turkey_output, target=VOUCHER_MAX):
    '''
    :param: turkey_output = name of the file to output
    :param: target  = the number of coded number tagged vouchers to output

    this function calls key_code_generator() and code_string() to generate
    and format code numbers and then creates _target_ number of vouchers with
    _target_ number of codes

    It then uses xlsxwriter to drop the various text strings into an excel file
    and keeping everything spaced out properly.
    
    '''
    off_set = 18
    spot_counter = 0 # to keep track of where things are in the page
    ID_counter_store = 1 # incrementor for the 'ID log sheet'
    
    codes = key_code_generator(target)
    turkey_codes = code_string(codes)

    
    workbook = xlsxwriter.Workbook(turkey_output)
    bold = workbook.add_format({'bold': True})
    worksheet = workbook.add_worksheet('turkey') # voucher workbook
    worksheet.set_margins(0.25,0.25,0,0) # Left,Right,Top,Bottom

    worksheet2 = workbook.add_worksheet('ID log') # a log of the ID numbers that we can print out
    
    

    l_n = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23] # reference positions

    for code in turkey_codes: # for code in formatted list of codes 
        
        code_ID = code # code string i.e. 1  8sJkl B4VHc 
        code_ID_cell = 'B{}'.format(l_n[13]) # cell Letter + number

        ID_log_cell = 'A{}'.format(ID_counter_store)

        # Filler text and name and address information for the recipient
        worksheet.write('A{}'.format(l_n[8]), 'KITCHENER TURKEY PICKUP TIMES:', bold)
        worksheet.write('A{}'.format(l_n[9]), 'Wed-Fri. Dec 4-6: 9:00am to 6:00pm')
        worksheet.write('A{}'.format(l_n[10]), 'Sat. Dec. 7: 9:00am to 4:00pm')
        worksheet.write('A{}'.format(l_n[11]), 'Sun. Dec. 8: 1:00pm to 4:00pm')
        worksheet.write('A{}'.format(l_n[12]), 'Mon-Wed. Dec. 9-11: 9:00am to 6:00pm')
        worksheet.write('A{}'.format(l_n[14]), 'Questions?  Call  519-742-5860', bold)

        worksheet.write('G{}'.format(l_n[8]), 'WATERLOO TURKEY PICKUP TIMES:', bold)
        worksheet.write('G{}'.format(l_n[9]), 'Wed-Sat. Dec 4-7: 11:00am to 4:00pm')
        worksheet.write('G{}'.format(l_n[10]), 'Sun. Dec. 8: CLOSED')
        worksheet.write('G{}'.format(l_n[11]), 'Mon-Wed. Dec. 9-11: 11:00am to 4:00pm')

        worksheet.write('A{}'.format(l_n[15]), 'ID # {}'.format(code_ID))
        #worksheet.write('A{}'.format(l_n[5]), 'Please bring a bag with you to carry the turkey',bold)
        worksheet.write('A{}'.format(l_n[6]), 'You MUST bring this voucher with you. Please bring a bag with you to carry the turkey.',bold)
        #worksheet.write('G' + str(l_n[10]), 'ID MAY BE REQUIRED.', bold)

        # write the code out in a separate sheet for reference
        worksheet2.write(ID_log_cell, code_ID)

        spot_counter += 1 
        ID_counter_store += 1 

        if spot_counter == 3: # adjust things for a new page
            off_set -= 2
            # use a full set of numbers in sequence to make it easier to add items later
            l_n[5] += off_set
            l_n[6] += off_set
            l_n[7] += off_set
            l_n[8] += off_set
            l_n[9] += off_set
            l_n[10] += off_set
            l_n[11] += off_set
            l_n[12] += off_set
            l_n[13] += off_set
            l_n[14] += off_set
            l_n[15] += off_set
            l_n[17] += off_set
            l_n[18] += off_set
            l_n[19] += off_set
            l_n[20] += off_set

            spot_counter = 0
            off_set += 2
            
        else: # space every cell out by the standard measure
            # use a full set of numbers in sequence to make it easier to add items later
            l_n[5] += off_set
            l_n[6] += off_set
            l_n[7] += off_set
            l_n[8] += off_set
            l_n[9] += off_set
            l_n[10] += off_set
            l_n[11] += off_set
            l_n[12] += off_set
            l_n[13] += off_set
            l_n[14] += off_set
            l_n[15] += off_set
            l_n[17] += off_set
            l_n[18] += off_set
            l_n[19] += off_set
            l_n[20] += off_set
    
    workbook.close()

# WRITING FUNCTION CALLS

write_turkey_vouchers(turkey_output, target=4500)
print('turkey vouchers output')



